package it.unisalento.pps.model;
// Generated 26-set-2017 0.37.54 by Hibernate Tools 5.1.5.Final

import it.unisalento.pps.dao.DisciplinaDAO;

/**
 * Disciplina generated by hbm2java
 */
public class Disciplina {

	private int idDisciplina;
	private String nome;
<<<<<<< HEAD
	private double costoMensile;
=======
	private String costoMensile;
>>>>>>> branch 'master' of https://github.com/donatocatalano/centrosportivo.git
	private String immagine;
	private String descrizione;

	public Disciplina() {
	}

	public Disciplina(int idDisciplina) {
		this.idDisciplina = idDisciplina;
	}

<<<<<<< HEAD
	public Disciplina(int idDisciplina, String nome, double costoMensile, String immagine, String descrizione) {
=======
	public Disciplina(int idDisciplina, String nome, String costoMensile, String immagine, String descrizione) {
>>>>>>> branch 'master' of https://github.com/donatocatalano/centrosportivo.git
		this.idDisciplina = idDisciplina;
		this.nome = nome;
		this.costoMensile = costoMensile;
		this.immagine = immagine;
		this.descrizione = descrizione;
	}

	
	public int getIdDisciplina() {
		return this.idDisciplina;
	}

	public void setIdDisciplina(int idDisciplina) {
		this.idDisciplina = idDisciplina;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

<<<<<<< HEAD
	public double getCostoMensile() {
=======
	public String getCostoMensile() {
>>>>>>> branch 'master' of https://github.com/donatocatalano/centrosportivo.git
		return this.costoMensile;
	}

	public void setCostoMensile(String costoMensile) {
		this.costoMensile = costoMensile;
	}

	public String getImmagine() {
		return this.immagine;
	}

	public void setImmagine(String immagine) {
		this.immagine = immagine;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}
	/*
	public static Corso findCorsoByCodice(String codCorso) {
		return CorsoDAO.getInstance().findByCodice(codCorso);
	}*/

}
