package it.unisalento.pps.model;
// Generated 26-set-2017 0.37.54 by Hibernate Tools 5.1.5.Final



/**
 * Disciplina generated by hbm2java
 */
public class Disciplina {

	private int idDisciplina;
	private String nome;
	private float costoMensile;
	private String immagine;
	private String descrizione;

	public Disciplina() {
	}

	public Disciplina(int idDisciplina) {
		this.idDisciplina = idDisciplina;
	}

	public Disciplina(int idDisciplina, String nome, float costoMensile, String immagine, String descrizione) {
		this.idDisciplina = idDisciplina;
		this.nome = nome;
		this.costoMensile = costoMensile;
		this.immagine = immagine;
		this.descrizione = descrizione;
	}

	public int getIdDisciplina() {
		return this.idDisciplina;
	}

	public void setIdDisciplina(int idDisciplina) {
		this.idDisciplina = idDisciplina;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public float getCostoMensile() {
		return this.costoMensile;
	}

	public void setCostoMensile(float costoMensile) {
		this.costoMensile = costoMensile;
	}

	public String getImmagine() {
		return this.immagine;
	}

	public void setImmagine(String immagine) {
		this.immagine = immagine;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

}
