package it.unisalento.pps.model;
// Generated 26-set-2017 0.37.54 by Hibernate Tools 5.1.5.Final

/**
 * Livello generated by hbm2java
 */
public class Livello {

	private int idLivello;
	private String nome;

	public Livello() {
	}

	public Livello(int idLivello) {
		this.idLivello = idLivello;
	}

	public Livello(int idLivello, String nome) {
		this.idLivello = idLivello;
		this.nome = nome;
	}

	public int getIdLivello() {
		return this.idLivello;
	}

	public void setIdLivello(int idLivello) {
		this.idLivello = idLivello;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

}
