package it.unisalento.pps.model;
// Generated 26-set-2017 0.37.54 by Hibernate Tools 5.1.5.Final

/**
 * Spazio generated by hbm2java
 */
public class Spazio{

	private int idSpazio;
	private String nome;

	public Spazio() {
	}

	public Spazio(int idSpazio) {
		this.idSpazio = idSpazio;
	}

	public Spazio(int idSpazio, String nome) {
		this.idSpazio = idSpazio;
		this.nome = nome;
	}

	public int getIdSpazio() {
		return this.idSpazio;
	}

	public void setIdSpazio(int idSpazio) {
		this.idSpazio = idSpazio;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

}
