package it.unisalento.pps.model;
// Generated 26-set-2017 0.37.54 by Hibernate Tools 5.1.5.Final

/**
 * Tipopagamento generated by hbm2java
 */
public class TipoPagamento {

	private int idTipoPagamento;
	private String tipo;

	public TipoPagamento() {
	}

	public TipoPagamento(int idTipoPagamento) {
		this.idTipoPagamento = idTipoPagamento;
	}

	public TipoPagamento(int idTipoPagamento, String tipo) {
		this.idTipoPagamento = idTipoPagamento;
		this.tipo = tipo;
	}

	public int getIdTipoPagamento() {
		return this.idTipoPagamento;
	}

	public void setIdTipoPagamento(int idTipoPagamento) {
		this.idTipoPagamento = idTipoPagamento;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

}
