package it.unisalento.pps.model;
// Generated 26-set-2017 0.37.54 by Hibernate Tools 5.1.5.Final

/**
 * Tipoevento generated by hbm2java
 */
public class TipoEvento {

	private int idTipoEvento;
	private String tipo;

	public TipoEvento() {
	}

	public TipoEvento(int idTipoEvento) {
		this.idTipoEvento = idTipoEvento;
	}

	public TipoEvento(int idTipoEvento, String tipo) {
		this.idTipoEvento = idTipoEvento;
		this.tipo = tipo;
	}

	public int getIdTipoEvento() {
		return this.idTipoEvento;
	}

	public void setIdTipoEvento(int idTipoEvento) {
		this.idTipoEvento = idTipoEvento;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

}
